include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    avoid_field_initializers_in_const_classes: ignore
    close_sinks: ignore
    missing_required_param: error
    missing_return: error

  exclude:
    - test/**
    - lib/generated_plugin_registrant.dart
    - lib/firebase_options.dart
    - lib/**.g.dart
