name: basic_app_info
description: "App Info Package"
homepage: "https://tguzel.dev"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: ">=3.24.4"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1

dev_dependencies:
  very_good_analysis: ^6.0.0